PrivateBin/PrivateBin

- README.md
Corrects a small spelling error.
> Correct spelling error.

- cfg/conf.ini.sample
> ZeroBin -> PrivateBin

- lib/i18n.php
https://github.com/PrivateBin/PrivateBin/issues/41
Not tested locally, let's say what Travis says... :smile:
> Change array used for language selection

- css/bootstrap/privatebin.css
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/66
* Removed old CSS, which only targeted the left element
* Added general margin, which targets all navigation elements now
* Removed padding of password-input, because the right & left padding is unnecessary here as we now use the margin to move it away from the elements near it.
> Add margin for all nav elements

- i18n/fr.json
This PR fixes some french translation issues
* Update i18n/fr.json
> Fix some french translation issues (typo + minor problems).

- CREDITS.md
* Split in active contributors & old contributors.
> Renew credits

- i18n/it.json
- js/privatebin.js
* [✓] I agree to release the changes in this PR under the Zlib/libpng license as shown in the  [LICENSE file](https://github.com/PrivateBin/PrivateBin/blob/master/LICENSE.md#zliblibpng-license-for-privatebin).
*  Added i18n/it.json
*  Updated js/privatebin.js, added 'it' as supported language
> Italian translation

- i18n/de.json
- js/privatebin.js
- tpl/bootstrap.php
This PR fixes issue #69
* Added bootstraps' modal dialog to tpl/bootstrap.php with password input box
* Added/corrected relevant JS code to handle it on decryption
* Updated integrity hash
It works, but code/HTML is preliminary and probably not perfect :)
> Modal (custom) decryption password (solves #69)

- js/privatebin.js
- tpl/bootstrap-compact.php
- tpl/bootstrap-dark-page.php
- tpl/bootstrap-dark.php
- tpl/bootstrap-page.php
- tpl/bootstrap.php
- tpl/page.php
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/140
> Add table class to parsed Markdown

- i18n/es.json
- js/privatebin.js
* Added translation file es.json 
* Modified privatebin.js to show new supported language
> Added Spanish Translation

- i18n/oc.json
Just made an occitan version, in its lengadocian dialecte.
This PR fixes 
* 
*
> Occitan locale file

- js/language
in order to show occitan translations
This PR fixes 
* 
*
> oc added to supported languages

- cfg/conf.ini.sample
Changed "Mibibytes" to "Megabytes"
[X] To the extent possible under law, I have waived all copyright and related or neighboring rights to this PR and publish it as public domain.
> Fixed a spelling error in conf.ini

- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
Fixes https://github.com/PrivateBin/PrivateBin/issues/126
* New state (only new button) added
* Shown when the message cannot be decrypted.
Just test…
> New state for "only new button"

- i18n/pt.json
- js/privatebin.js
Support Portugues translation for PrivateBin by adding its corresponding
file.
> Add Portuguese Translation file

- .eslintrc
- .travis.yml
- composer.json
- css/bootstrap/privatebin.css
- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/it.json
- i18n/no.json
- i18n/oc.json
- i18n/pl.json
- i18n/ru.json
- i18n/sl.json
- i18n/zh.json
- js/privatebin.js
- js/test.js
- tpl/bootstrap.php
- tpl/page.php
- tst/PrivateBinTest.php
- tst/ViewTest.php
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/178
Also fixes https://github.com/PrivateBin/PrivateBin/issues/76, fixes https://github.com/PrivateBin/PrivateBin/issues/176, fixes https://github.com/PrivateBin/PrivateBin/issues/187
* Revealing Module Pattern
* "state" concept abandoned, now each module handles it's state internally (that's more flexible)
* more modules…
* a bit more console logging…
* clicking on "new" does not reset expiration/format/… values. (that's acceptable for now IMHO)
> [WIP] JS refactoring with revealing module pattern

- i18n/zh.json
Add missing translations in Chinese，and modified some typo from Traditional Chinese to Simplified Chinese
[✓] I agree to release the changes in this PR under the Zlib/libpng license as shown in the [LICENSE file](https://github.com/PrivateBin/PrivateBin/blob/master/LICENSE.md#zliblibpng-license-for-privatebin).
> Update zh.json - Add missing translations

- i18n/fr.json
* few translations completed in french
> fr translation completed

- i18n/pt.json
Just a minimal change on the translation which I tracked from Issue #201
> Update pt.json to reflect latest string changes

- i18n/ru.json
This PR updates the translation for two strings.
> Update Russian translation

- i18n/fr.json
In french we say "chiffrer" and "déchiffrer", "chiffrage" has another meaning.
I also added missing translations.
> Corrections and missing translations

- README.md
Fixes a few more minor grammar mistakes
> README: Fix some minior grammar mistakes

- i18n/oc.json
* proper non breaking spaces
* proper ' in Occitan
* new strings translated
> Correction typo + new strings

- i18n/es.json
This PR fixes 
* Updated latests IDs for spanish translation (es.json)
> Updated spanish translation

- Dockerfile
- docker-compose.yml
- docker/entrypoint.sh
Hi everyone.
This PR primarily adds a volume for the data directory and a config for Docker-Compose for easier deployment.
* Minor fixes to Dockerfile
* && instead of semicolon
* Full path (Be more explicit, better to read imho)
* Fix libpng pacakge name
* Define a volume for the data directory
* Add entrypint.sh script to fix permissions on data directory
* Added docker-compse config
> Add VOLUME for data directory and Docker-Compose config

- i18n/oc.json
New strings translated + some corrections
> Update Occitan translation

- tpl/bootstrap.php
Remove conflict marker, put back all the indention (that I could catch?)
> Fix bootstrap template

- i18n/nl.json
- js/privatebin.js
This adds a nl.json file & udpates the array of available languages in privatebin.js
The security hash for privatebin.js needs to be regenerated & updated in the template files
> Adding NL (Dutch) translation

- i18n/hu.json
- js/privatebin.js
This PR adds 
* Hungarian translation
* Hun language selector
* [Regenerate SRI hashes]
> New Hungarian translation file

- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
This PR fixes an issue displaying sent comments on pretty printed pastes. They are sent correctly and displayed when the page is reloaded, but after hitting the "send comment" the UI just stops and doesn't display the sent comment. This is likely a regression of the JS refactoring.
> Fixing comments on pretty printed pastes

- i18n/oc.json
> [i18n]Update translation for Occitan

- i18n/de.json
* Change de.json for more consistency in naming
* Change de.json in order to achieve better reading-flow
> Improve German Translation for more consistency

- js/common.js
- js/privatebin.js
- js/test/Model.js
- js/test/Prompt.js
- lib/Request.php
- tpl/bootstrap.php
- tpl/page.php
- tst/ConfigurationTestGenerator.php
- tst/ControllerTest.php
- tst/JsonApiTest.php
- tst/RequestTest.php
This implements test to replicate and fixes #396.
> Facebook tracking parameter test & fix

- i18n/pl.json
This PR simply fixes some small misunderstandings and typos in polish translation.
> Update polish translation.

- js/base-x-3.0.5.1.js
- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
This PR fixes #377
You can test this at https://privatebin.at
* Added a modified version of base-x.js
* Encode the symmetric key as base58
> Encode key as base58

- i18n/fr.json
Translation of untranslated sentences + Improved translation of one sentence
> Upgrade french translation

- i18n/oc.json
Use of è form for correctly corrèctament
Use of subjunctive after "in case", se per cas + subjectiu
> [i18]Update and corrections for Occitan

- SECURITY.md
> create security.md for new Github security feature

- tpl/bootstrap.php
This PR fixes 
https://github.com/PrivateBin/PrivateBin/issues/477
* Move the send button out of the collapsable toolbar and put it into the right top coner of the editor.
* Add warnning below URL shortener(if enabled) and move the URL shortener button out of the alert in order to avoid style shifting.
> #447 Rework UX to address obscured send button and hard to click URL shortener button

- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
…
This PR fixes 
https://github.com/PrivateBin/PrivateBin/issues/479
https://github.com/PrivateBin/PrivateBin/issues/484
https://github.com/PrivateBin/PrivateBin/issues/354
1. The address bar is not cleared when creating new paste from existing paste. This is fixed.
2. The URL shortener integration is poor, it is enhanced.
3. The discussion is not cleared when new/clone paste is clicked.
> #479 Enhance URL shortener integration, clear address bar and discussion when create new paste from existing paste

- css/bootstrap/privatebin.css
- css/privatebin.css
- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
This PR fixes 
https://github.com/PrivateBin/PrivateBin/issues/487
https://github.com/PrivateBin/PrivateBin/issues/317
* 
*
> Improve drag & drop UI, handle the case where user cancelled attachment selection properly

- css/bootstrap/privatebin.css
- css/privatebin.css
This PR fixes 
https://github.com/PrivateBin/PrivateBin/issues/495
https://github.com/PrivateBin/PrivateBin/issues/492
* 
*
> Automatically switch layout to use fluid container if window is wider than certain value

- cfg/conf.sample.php
- js/privatebin.js
- lib/Configuration.php
- tpl/bootstrap.php
- tpl/page.php
Fix click on new paste on clone paste editing view not removing custom attachment
Fix cloning paste with attachment
Update CSP in sample and default configuration
Ensure clone paste also clone format
Fix clone button hiding logic when paste is burn after read
Remove attachment name when new paste clicked on
Update SRI
This PR fixes 
https://github.com/PrivateBin/PrivateBin/issues/494
https://github.com/PrivateBin/PrivateBin/issues/493
https://github.com/PrivateBin/PrivateBin/issues/491
https://github.com/PrivateBin/PrivateBin/issues/489
https://github.com/PrivateBin/PrivateBin/issues/497
> Bug bash for 489, 491, 493, 494, 497

- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
This PR fixes 
#505 
Where an undesired assumption is introduced, when the textarea is visible, it doesn't really equivalent to attachment being editable. This piece of logic is now refactored.
* 
*
>  Refactor attachment editable detection logic to avoid undesired assumption

- .htaccess.disabled
- INSTALL.md
This PR adds PHP configuration to allow uploading bigger files.
> Allow to upload bigger files

- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
This PR fixes 
Closes #527
* 
*
> Bugfix: when password is disabled in config no new paste can be     created

- i18n/oc.json
> [i18n] Occitan locale

- i18n/fr.json
This PR fixes 
* Add mail modal & content fr translation
> Mail fr translation

- i18n/fr.json
- i18n/oc.json
Corrects some French and update the Occitan file.
> i18n Update French and Occitan files

- i18n/pt.json
This PR handles untranslated keys in `pt.json`, mentioned in #201
> Update pt translation

- .github/workflows/php.yml
GitHub has these new CI/CD features, so let's test whether this makes sense.
I guess this PHP thing just installs the project via composer… :thinking:
> Test PHP Composer runner of GitHub

- i18n/zh.json
This PR translated keys in zh.json, mentioned in #201
> Update Chinese translation.

- i18n/bg.json
- i18n/cs.json
- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/hu.json
- i18n/it.json
- i18n/nl.json
- i18n/no.json
- i18n/oc.json
- i18n/pl.json
- i18n/pt.json
- i18n/ru.json
- i18n/sl.json
- i18n/uk.json
- i18n/zh.json
- tpl/bootstrap.php
- tpl/page.php
Just useless templates/defaults without any content.
Fixes https://github.com/PrivateBin/PrivateBin/issues/139
/cc @paulcmal @ajvsol
> Add OpenGraph and Twitter cards

- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/611
The expiration time is not reset anyway, because we do not have the default value saved anywhere. (would need a template change) And even if so we'd need to lookup how to change that in that bootstrap component.
Anyway, this PR makes it better than currently, which does not reset anything if you (STR):
1. Create new paste. (Do NOT click the generated link)
2. Click on "New".
> Reset options when clicking on "New Paste"

- i18n/oc.json
To cover: handle review commentes
> i18n update Occitan language

- cfg/conf.sample.php
- js/privatebin.js
- js/test/Helper.js
- lib/Configuration.php
- tpl/bootstrap.php
- tpl/page.php
This PR fixes bugfixes section of #625 
1.  Add resource: to script-src cspheader to fix pdf display in Firefox
2.  Cannot paste text into password input dialog
3.  Avoid DOMPurify mess with forward slash in expirationDateString
4.  Fix broken Helper.durationToSeconds, as it doesn't handle weeks
5.  Reload page when back button in browser pressed, avoid reading burn after read paste from cache
6.  Fix TopNav.isAttachmentReadonly logic so dropzone won't show when shouldn't
7.  Change order of execution to detect delete token properly
8.  Sanitize output from Helper.urls2links
9.  Avoid recreation of existing pasteurl element when calling URL shortener
10. Open all links in new window
Test deployment:
https://privatebin-testing.herokuapp.com/
> 625 bugfixes - excluding attachment preview handling bugfixes

- i18n/ru.json
> i18n: update russian translation

- i18n/de.json
This PR fixes a grammar mistake in the German translation.
> Fix grammar

- i18n/es.json
> Update spanish translation

- i18n/en.json
Add plurals for `Please wait %d seconds between each post` and fix translable strings in `This document will expire in` message (add dot at end).
> [i18n] Update en strings

- tpl/bootstrap.php
Fixes language selection dropdown issue.
> Language dropdown menu to the right

- INSTALL.md
This role simply deploys PrivateBin on your servers, it's functionality
is quite limited and currently does not support further hardening
techniques[^0]. But however, I think it is beneficial for quite a lot of
people.
[^0]: https://todo.sr.ht/~e1mo/ansible-role-privatebin/1
> Add link to PrivateBin ansible role

- codacy-analysis.yml
It should now be included into GitHub's security tab.
Fixes https://github.com/PrivateBin/PrivateBin/issues/741
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/741
> Let's try Codacy code scanning again

- cfg/conf.sample.php
- composer.json
- composer.lock
- lib/Configuration.php
- lib/Persistence/TrafficLimiter.php
This PR adds an option in config to exempt ips from being hit by the ratelimiter.
* Added a exemptedIp config option in conf.php
* Added an extra check in TrafficLimiter.php
> Make it possible to exempt ips from the rate-limiter

- .github/workflows/snyk-scan.yml
After I found https://github.com/PrivateBin/docker-nginx-fpm-alpine/pull/44 I saw they also support PHP, so let's do it here (one level before container packaging), too.
Also it complements the CodeQL analysis, which only covers the JS part.
I added the API token to the PrivateBin org now.
Ref https://github.com/PrivateBin/PrivateBin/issues/504 and https://github.com/PrivateBin/PrivateBin/issues/741
> Add Snyk security scan for PHP

- lib/Data/GoogleCloudStorage.php
- tst/Data/GoogleCloudStorageTest.php
This PR fixes provides the simplest implementation of a key value store on GCS, with unit tests. This runtime behaviour/performance will be tested and I expect an optimised implementation to follow.
* added getValue and setValue on GoogleCloudStorage
* added unit tests.
> simplest implementation of kv support on gcs

- lib/Data/GoogleCloudStorage.php
- tst/Data/GoogleCloudStorageTest.php
This PR added the purgeValues function
* implementation
* unit tests
> added purgeValues function

- lib/Data/GoogleCloudStorage.php
- tst/Data/GoogleCloudStorageTest.php
This PR improves the implementation of get, set and purge values.
* set values will store the value in the GCS object metadata for the non-salt namespaces
* purge values will use metadata to filter objects to delete
* unit test for purge values separated
> improved implementation

- lib/Data/GoogleCloudStorage.php
- tst/Data/GoogleCloudStorageTest.php
This PR removes the json encode from get/setValue
* json encoding/decoding removed
* updated unit test to store and test strings
* removed duplicate unit test code
> removed json encoding from get/setValue

- INSTALL.md
Fixes https://github.com/PrivateBin/PrivateBin/issues/822
> Clarify download instruction from GitHub releases

- .github/workflows/tests.yml
Should display the erros inline: https://github.com/shivammathur/setup-php#problem-matchers
> Setup CI problem matchers for PHP

- CHANGELOG.md
- CREDITS.md
- INSTALL.md
- lib/Data/Database.php
- tst/Data/DatabaseTest.php
> Support running PrivateBin on OCI (Oracle Database), Part 2

- cfg/conf.sample.php
- lib/Configuration.php
- lib/Controller.php
Made fixes to my whitelist PR suggested by @rugk
> Whitelist Paste Creation (not reading)

- i18n/zh.json
Update zh translation in zh.json
> Update zh translation

- .github/workflows/snyk-scan.yml
- CHANGELOG.md
- CREDITS.md
- i18n/tr.json
- js/privatebin.js
- lib/I18n.php
- tpl/bootstrap.php
- tpl/page.php
- credit & document Turkish translation
- remove plural indicators
- add plural logic and enable Turkish translation
- bump github/codeql-action from 1 to 2
> Enable Turkish translation

- .github/workflows/tests.yml
- js/package-lock.json
NodeJS v16.14.0
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/953
> Add missing package-json.lock

- CHANGELOG.md
- CREDITS.md
- INSTALL.md
- cfg/conf.sample.php
- composer.json
- lib/Configuration.php
- lib/Data/S3Storage.php
* implemented an S3 storage backend, similar to GoogleCloudStorage.php
* based on AWS SDK for PHP
* successfully tested against Rados object gateway (CEPH)
* added documentation and configuration knobs
* test against AWS cloud storage
> implemented S3 storage backend

- lib/Controller.php
- tst/JsonApiTest.php
> expose types JSON-LD incl. configured expiration dates

- lib/Data/Filesystem.php
- lib/Filter.php
- lib/I18n.php
- lib/Request.php
- lib/Vizhash16x16.php
- tst/Bootstrap.php
- tst/JsonApiTest.php
This PR fixes #1084 
* applied slightly modified StyleCI patch
> apply StyleCI patch, fixes #1084

- .github/workflows/shiftleft-analysis.yml
It seems [to cover](https://slscan.io/en/latest/#supported-languages-frameworks) PHP including license check in addition to dependency scanning.
Ref https://github.com/PrivateBin/PrivateBin/issues/504 and https://github.com/PrivateBin/PrivateBin/issues/741
> Add Shiftleft scan

- .github/ISSUE_TEMPLATE/config.yml
Likely that online VSCode did a stupid line wrapping here, let's see whether that works.
This PR fixes https://github.com/PrivateBin/PrivateBin/pull/1134/files#r1288852494
> Fix potential syntax error in YAML

- .github/ISSUE_TEMPLATE/config.yml
Was worth a try, but apparently markdown is not supported there.
This PR fixes 
* 
*
> Remove markdown from issue selector

- .github/DISCUSSION_TEMPLATE/q-a.yml
- .github/ISSUE_TEMPLATE/feature_request.md
This PR fixes #1143 (maybe... ;-) )
* dropdown instead of radio button
* standardize the form attributes
We may have to do some additional iterations until we are happy with the result. Here goes one more attempt.
> Template tweaks

- .github/DISCUSSION_TEMPLATE/q-a.yml
> Update discussion template

- doc/Installation.md
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/1159
* https://github.com/PrivateBin/PrivateBin/commit/172efafb817926f74e86c534934b8719d761eac4 - List of two Ansible roles.
* https://github.com/PrivateBin/PrivateBin/commit/42cf45542fe08526e0c4321960728d6374e22e27 - Consistency correction due to the previous commit.
> Doc installation ansible

- cfg/conf.sample.php
- lib/Configuration.php
- lib/Controller.php
- tpl/bootstrap.php
- tpl/page.php
- tst/ViewTest.php
> feat: make the email button optional.

- doc/Installation.md
This PR fixes the install documentation. 
* CONFIG_PATH should actually point to the directory that contains the conf.php file.
* As discussed [here](https://github.com/orgs/PrivateBin/discussions/1162#discussioncomment-6971885) privatebin should be equipped with a proper loggin system helping to troubleshoot this kind of issues.
> Fix install docs

- doc/Installation.md
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/1180
* Ansible Galaxy Links - https://github.com/PrivateBin/PrivateBin/commit/9a4c5b30c6c24aed8af302e1261481455c0531af
> Update Ansible Galaxy links in Installation.md

- .github/workflows/tests.yml
A try following https://github.com/PrivateBin/PrivateBin/pull/1189#pullrequestreview-1695447526
> Use Node20 for tests

- .vscode/settings.json
This PR fixes #1211
* Add .vscode/settings.json
* Configure all files matching "**/cfg/conf*.php" to be treated as INI for syntax highlighting in VSCode
N/A
> add workspace settings with config files treated as INI

- doc/Release.md
…WIP)
This documents/should document:
* what the signatures are and what they proof
* how to verify them
* how to build releases (I know more of a maintainer doc, but yeah, I found it a good place here, if you want a separate one feel free)
This should also make it easier for other maintainers to create releases or so.
@elrido feel free to adjust/push to the branch if you want to have some details fixed. I have left some TODOs of stuff where I am unsure.
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/1169#issuecomment-1857869357
> Created doc for “how to verify and how to do release” (release doc)

- doc/Installation.md
fixes #1222
Any feedback/suggestions for improvements appreciated.
> improve SDK install docs

- CHANGELOG.md
- js/common.js
- js/package-lock.json
- js/privatebin.js
- js/test/PasteStatus.js
- tpl/bootstrap.php
- tpl/page.php
This PR (attempts to) fixes #1224
* relax URL finding regex
* but add a filter based on built-in URL class, relying on browsers to validate potential URLs
> Shortener URL validation improvement

- .gitattributes
- composer.lock
- doc/Installation.md
- clarify installation instructions for non-included composer packages
- ensure composer files get released in exported archive
- fix lock checksum
> composer fixes for #1222

- i18n/en.json
- i18n/fr.json
Includes french translation.
This PR fixes  #946 
* "Send" button label
* French translation of "Send" button label
> Change "Send" button label to "Save"

- doc/Release.md
Apparently the headline changed, this is the direct link for GitHub.
ref https://github.com/orgs/PrivateBin/discussions/1247#discussioncomment-8493081
> doc: Fix (direct) link to SLSA verifier

- lib/Controller.php
This PR fixes #1262 
* Added `Controller->_setCacheHeaders()`
* Invoke from `Controller->__construct()`
> Always add cache control headers

- cfg/conf.sample.php
- lib/Request.php
- tst/JsonApiTest.php
This PR relates to #1002 
* Allow `${basepath}?shortenviayourls&link=` to trigger URL shortening
Note: I'm having trouble running the tests in my fork, so I'm marking this as a draft until I get the tests sorted out.
> Allow for shortenviayourls in query params

- i18n/it.json
* Just a fixed translation (the original was quite silly in Italian...)
> Fix weird Italian translation for burn-after-reading messages.

- CHANGELOG.md
- tpl/bootstrap5.php
This PR closes #1317
* Nav bar & footer improvements suggested by @proton-ab
> bootstrap 5 nav bar & footer improvements

- i18n/nl.json
* Added new (missing) strings
* Fixed incorrect translations
> feat(translations): add new Dutch strings

- js/test/TopNav.js
Added test case to verify rawText manipulates button visibility correctly.
> Added test case to verify rawText

- js/privatebin.js
This PR fixes issue #1293. 
*  Modify the `downloadText()` method in the `privatebin.js` file.
> fix: downloadText() method to accommodate .md file format

- js/privatebin.js
- tpl/bootstrap.php
- tpl/bootstrap5.php
- tpl/page.php
This PR fixes #1194. 
*  Add a new method called `clearPasswordInput()` akin to `clearAttachment()`
*  Call this method in the `resetInput()` method. 
* Add SRI hashes for the changes introduced.
> fix: reset password input field on creation of new paste

- CHANGELOG.md
- js/dark-mode-switch.js
- tpl/bootstrap5.php
This PR fixes #1340
* initialize including browser preferences, not just from local storage
> bootstrap5 dark mode toggle unset on dark browser preference

- i18n/oc.json
This PR updates the Occitan translation file
> i18n: Update Occitan locale

- .devcontainer/postCreateCommand.sh
- js/privatebin.js
- lib/Configuration.php
Fixes https://github.com/PrivateBin/PrivateBin/issues/1420
I have not tested it practically (just a quick hotfix), but given the code history and this was what worked before, I guess this should work. 🙃
(Edit: and sorry for the commit message, i stopped typing and was too fast clicking through stuff… can force-push if needed or so)
> Fix paste link not always being included in mail 

- css/bootstrap/privatebin.css
- css/bootstrap5/privatebin.css
This PR fixes 
* Long URL in plaintext breaks responsive design on small screen
> fix: responsive long url in plaintext

- CHANGELOG.md
- js/privatebin.js
- lib/Configuration.php
This PR fixes #92
* Now on language dropdown item click JS reloads the page instead of redirecting to the home page
Test website: https://test.ribas160.ru/privatebin/
> Keep paste URL, if changing language in dropdown

- CHANGELOG.md
- CREDITS.md
- css/bootstrap5/privatebin.css
- tpl/bootstrap5.php
This PR closes
The PR doesn't related to the main problem described in the #1391 issue. So, I didn't add it to *closes*.
* Increase navbar margin bottom, centralize button icons on bootstrap5 template
Test website: https://test.ribas160.ru/privatebin/
> Bootstrap5 template improvements

- js/common.js
- js/privatebin.js
- js/test/CopyToClipboard.js
- lib/Configuration.php
This PR is a continuation of #1475
* Unit tests for CopyToClipboard js class added
I need an advice from the experienced developer and I would like to ask a few questions if you don't mind :)
In "copy with button click" test I also used `PasteViewer` class
```js
jsc.property('Copy with button click', common.jscFormats(), 'nestring', function (format, text) {
var clean = jsdom();
$('body').html(
'<div id="placeholder" class="hidden">+++ no paste text ' +
'+++</div><div id="prettymessage" class="hidden">' +
'<button type="button" id="prettyMessageCopyBtn"><svg id="copyIcon"></svg>' +
'<svg id="copySuccessIcon"></svg></button><pre ' +
'id="prettyprint" class="prettyprint linenums:1"></pre>' +
'</div><div id="plaintext" class="hidden"></div>'
);
$.PrivateBin.PasteViewer.init(); …
```
> CopyToClipboard unit tests

- i18n/fr.json
This PR fixes new translation in fr.json
* translate new sentences
* add `/Cmd+c` in previous translation
> update new translation in fr.json

- js/privatebin.js
- lib/Configuration.php
This PR fixes #1575 
* Duplicate attachment for every comment fixed
* Attachments with empty file names fixed
Test website: https://test.ribas160.ru/PrivateBin
> Attachment bugs fixes

- CHANGELOG.md
- js/privatebin.js
- lib/Configuration.php
This PR fixes #1584 
* Name mismatches in attached files fixed
Test website: https://test.ribas160.ru/privatebin
> Name mismatches in attached files fixed
