- INSTALL.md
* Fixes HTTPS links to php.net - due to php's site mirroring architecture we cannot assume that it's available via HTTPS in every case (let's say it - it's not). Special one - `secure.php.net` - needs to be used. I can expand on that if anyone is really interested.
> Fix HTTPS links to php.net

- css/bootstrap/darkstrap-0.9.3.css
- css/bootstrap/privatebin.css
- css/privatebin.css
The current icon is way too small and the padding was still the one used when we had the text title there...
New version:
> Improve icon display

- js/privatebin.js
- tpl/.editorconfig
- tpl/bootstrap.php
- tpl/page.php
Fixes https://github.com/PrivateBin/PrivateBin/issues/172
* Added #loadingindicator
* New state: "SubmittingPaste"
* SubmittingPaste hides all buttons and displays #loadingindicator
* SubmittingPaste is triggered when a user clicks on the "Send" button and reverted (with state NewPaste) when the submission fails
> Add loading indicator

- i18n/es.json
Deleted extra space between [% s].
Correction suggested by @tmelikoff
> Update es.jason - syntax correction

- tpl/page.php
We don't need to mention Safari, as apple has dropped support for Windows anymore, and since Internet Explorer isn't on Macs, there should be little to worry about :p
* Removed the mentioning of Safari when using internet explorer.
> Safari isn't available on Windows anymore

- i18n/pt.json
As referenced on issue #201, some IDs were missing from the pt translation, which were now translated.
> Translate missing IDs to Portuguese

- i18n/it.json
- new strings translated
- couple of minor errors fixed
Some strings (i.e. line 133) are literal translations.
I could probably give a better translation by reading the messages in
their context, when I get the next update.
> Italian Translation update

- tpl/bootstrap.php
The text "password (recommended)" on the password field was being truncated to "password (recommen" because of a size issue.
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/231
* Expanded the password field to 23 in size to prevent the help text from being truncated. (affected all major browsers - excluding mobile).
> Updated bootstrap.php to fix a display issue

- tpl/bootstrap.php
Move URL shortener out of `#pastelink` as that is overwritten by the JS. (IMHO it makes no sense anyway to have it inside `#pastelink`. 
Fixes https://github.com/PrivateBin/PrivateBin/issues/280
I'll mark this as a braking change, as maybe someone's CSS depends on it, but I consider this very unlikely.
> Fix URL shortener button not being shown

- js/privatebin.js
- js/test/I18n.js
This PR fixes #296
If the language from the browser can not be detected, I've set the default language to "en".
> Default to en if browser does not provide a language

- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
This PR fixes #295 
Internet Explorer uses msSaveBlob.  I've had to bind a click event however.  I also swapped to using the Blob for the download link on other browsers instead of using the dataURI.
> Download Attachment changes.  Support for Edge and change to Blob

- .gitignore
- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
During testing of the jQuery upgrade I discovered this issue with the decryption of anonymous comments (= comments with no nickname property). That part of the code was last changed in the JS refactoring, so it could also be a regression from then.
> fix sending anonymous comments

- css/bootstrap/privatebin.css
- tpl/bootstrap.php
This makes the "Download attachment" link white in `bootstrap-dark` and `boostrap-dark-page`. This is an upstream bug of darkstrap, but it's not maintained anymore, so I think fixing it directly here is OK. It could also be fixed here:
https://github.com/PrivateBin/PrivateBin/blob/7f3339def0d0c241f6976904542d6a2a90095c6f/css/bootstrap/darkstrap-0.9.3.css#L5575-L5577
But I don't know if you want to edit that file, because it's an upstream file. But since it's not maintained anymore, it maybe would be a possibility? But for now I did it without it, but let me know if I should change it.
* Add new `dark-theme` class to body, which could also be used for other similar fixes of the dark theme (I don't know any at the moment, but I still thought it would be better to add it at the body and not …
> Fix download-link color in dark boostrap themes

- tpl/bootstrap.php
- tpl/page.php
Ask Google to not analyse the contents of the page for translation purposes
We already have i18n. Furthermore, Google may analyse sensitive content for
the purpose of recognising whether the page needs to be translated, see
https://support.google.com/webmasters/answer/79812?hl=en
(as it has reportedly been happened with Protonmail)
----
Hello dear user. Consider switching to Firefox. We can only ask Google's browser to not do it. We cannot prevent it...
---
adopted/credits from/to https://github.com/threema-ch/threema-web/pull/681 by @lgrahl (I hope the plain copy is okay :smile:)
> Ask Google not to translate the page

- .htaccess.disabled
This PR fixes #413.
I added a RewriteCond exception for Let's Encrypt bot so that it won't be denied by the next RewriteCond rule.
> Fix #413. Exclude Let's Encrypt bot from blacklisted bots

- js/privatebin.js
Leave IE with `msSaveBlob`, because it not support `blob:` uri too (at least my IE11 doesn't set uri to it).
Tested on Chromium 67 (x64, Win 8.1).
Fixes #432.
In addition, `$attachmentPreview` also can be used with blob, but it requires creating element with blob link as source.
> Use blob URI for saving attachments (#432)

- css/bootstrap/privatebin.css
- css/privatebin.css
This PR fixes 
The problem when:
1. The page is taller than viewport (scroll horizontally)
2. Drag and drop a file when the page is not scrolled to the top
3. The dropzone(blue overlay) will offset from window, partically visible
Example:
After the fix dropzone will always fit viewport.
* 
*
> Dropzone should be fixed to viewport, instead of fixed to sibling element

- INSTALL.md
- lib/Configuration.php
Closes #552 
I have put a very detailed description into the issue as to why I want to add this. I considered using a constant and adding a DEFINE to the index.php but for the use case this is more elegant.
* Query a `CONFIG_PATH` env var for the path to the config.php before using the default path.
* Nothing
> #552 Add support for a CONFIG_PATH env variable

- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
Fixes https://github.com/PrivateBin/PrivateBin/issues/534
**Please note**: This fix is only for the default, Bootstrap template. The template in tpl/page.php has the editor and preview buttons in a DIV with an ARIA-Hidden role, thus it needs more work to expose those controls to a screen reader as well.
> Fix ARIA for Editor/preview tabs.

- README.md
* remove old ZeroBin 0.19 guide, this is so old already, few people will benefit from a direct link in the Readme. It stays in the wiki for those, who need it.
* add direct link to the FAQ - it's one of our best documentation/sources, so it's a shame it is not featured more prominently 😉
> Feature FAQ link in Readme & remove legacy things

- i18n/sl.json
This PR fixes the info link in the footer of the sl translation. It was missing an "a" tag.
> Fixed info link in page footer of sl translation.

- i18n/bg.json
- i18n/cs.json
- i18n/de.json
- i18n/es.json
- i18n/fr.json
- i18n/hu.json
- i18n/it.json
- i18n/nl.json
- i18n/no.json
- i18n/oc.json
- i18n/pl.json
- i18n/pt.json
- i18n/ru.json
- i18n/sl.json
- i18n/uk.json
- i18n/zh.json
- js/privatebin.js
- js/test/I18n.js
- lib/I18n.php
- tpl/bootstrap.php
- tpl/page.php
- tst/I18nTest.php
While we currently have no indication of XSS in the PHP logic for translating strings, reviewing the `I18n:translate()` method I did find it not encode at all, so it would be susceptible to cause XSS in the future, where it used with user generated input. While this is unlikely to occur, due to most of the user generated content being handled client side, I'd still like to mitigate it, before it occurs.
Working on testing this and reviewing the use of the PHP translations, I also discovered and improved some other minor points. In particular, this PR changes:
- `I18n:translate()` will now encode all parameters, except integers and message IDs that contain links
- since the only case of `<br/>`-tag occurs on the PHP side (the noscript warning), I removed it from the allowed tags on the JS …
> Improve HTML entity encoding server side

- js/privatebin.js
- js/test/Helper.js
- tpl/bootstrap.php
- tpl/page.php
This PR fixes #588 - source code / plain text broken when containing HTML tags.
* refactor switch into nested if/else, to improve readability - no functional change, but helped me understand the intent of the logic
* revert Helper.urls2links() to be applied on top of HTML elements
* this allows the insertion of strings via text nodes, which makes the browser handle the HTML entity encoding for us
Plain text and source code now render correctly.
Markdown remains unchanged and unknown and risky HTML tags will still get stripped from it - this is intended, as far as I know. In [my tests](https://snip.dssr.ch/?8560054f84df4d13#26GKC5tiNspz58dzWCh1ev7AJEDLXhpKuzorLvAcQqep) I could still insert some HTML code inside of markdown-code blocks (3 backticks) and get a seemingly correct display. …
> Preview encoding fix

- i18n/fr.json
Up fr.json #642
"Encrypted note on PrivateBin":
"Message chiffré sur PrivateBin",
"Visit this link to see the note. Giving the URL to anyone allows them to access the note, too.":
"Visiter ce lien pour voir la note. Donner l'URL à une autre personne lui permet également d'accéder à la note."
> Up fr.json #642

- cfg/conf.sample.php
- lib/Configuration.php
- lib/Controller.php
- tpl/bootstrap.php
- tst/ViewTest.php
3 URLs of images used on social networks are passed in absolute URL.
Note that I did not pass all the images in absolute URLs, but, it could be consistent to do so, but, if the images work, maybe a relative call is more efficient?
Remove the version of PrivateBin, at the end of each image. This apparently prevents the opengraph from working, and, so I deleted on all of the images, to remain consistent at this level. This will make fewer requests, and, anyway, the images are not intended to change with each version.
> Make Opengraph really functional

- INSTALL.md
In the latest release 1.3.4, PHP 5.6 is the oldest supported version.
> Minimum PHP version is 5.6

- INSTALL.md
Migrated my PrivateBin instance to another server today and ran into this missing dependency.
* Add zlib extension to the install requirements
> Add zlib extension to requirements

- i18n/ar.json
- i18n/bg.json
- i18n/cs.json
- i18n/de.json
- i18n/el.json
- i18n/en.json
- i18n/es.json
- i18n/fr.json
- i18n/he.json
- i18n/hi.json
- i18n/hu.json
- i18n/it.json
- i18n/ja.json
- i18n/ku.json
- i18n/la.json
- i18n/lt.json
- i18n/nl.json
- i18n/no.json
- i18n/oc.json
- i18n/pl.json
- i18n/pt.json
- i18n/ru.json
- i18n/sl.json
- i18n/sv.json
- i18n/tr.json
- i18n/uk.json
- i18n/zh.json
- tpl/bootstrap.php
- tpl/page.php
This PR fixes a problem introduced with the commit eb32ea141956c0ed72e3186956895333f62e271c.
In the sentence "Data is encrypted/decrypted in the browser using 256 bits AES.", we saw "&lt;i&gt;in the browser&lt;/i&gt;" in normal font style in place of "<i>in the browser</i>" in italic.
As discussed on the [PR 755](https://github.com/PrivateBin/PrivateBin/pull/755), and [PR 754](https://github.com/PrivateBin/PrivateBin/pull/754), I keep the entire sentence in one translation object. I use sprintf to insert &lt;i&gt; and &lt;/i&gt;. Because I18n library already use sprintf (but escape HTML code in each argument), I need to tell it to explicitly return "%s" in the place where I need to insert the markups.
If it's ok, I will try to do the same work for all HTML markups currently present in …
> Avoid the use of <i> markup in a translation.

- README.md
HPKP has been removed by all major browsers and according to Can I use, it is only supported by browsers that have last received an update over a year ago - https://caniuse.com/?search=HPKP.
> Remove mention of HPKP in the README.

- CHANGELOG.md
- js/privatebin.js
- lib/Controller.php
- tpl/bootstrap.php
- tpl/page.php
This PR fixes #472 
* adds the `secure` flag to the cookie when set in JS and refreshed in PHP
This tells browsers only to transmit the cookie in a secure context. Apart from HTTPS, at least in Firefox, this also applies to local testing as 127.0.0.1 / localhost / ::1 are considered secure even when accessed over plain HTTP.
For live sites, this means that if they enable the `languageselection` feature, they do have to offer HTTPS or other secure means - would be interesting to know if e.g. tor is counted as such.
> Transmit cookie only over HTTPS

- cfg/conf.sample.php
- lib/Configuration.php
This follows an [HTTP Observatory recommendation](https://observatory.mozilla.org/analyze/privatebin.net):
> Restricts use of the <base> tag by using base-uri 'none', base-uri 'self', or specific origins.
Given we don't use that anywhere, this safe should be safe. (not tested practically though)
ref #108
> Add base URL as default CSP restriction

- lib/Controller.php
This PR is one of several ways to address a new feature being rolled out in Google Chrome called FloC. It is intended to be a more privacy oriented tracking mechanism then what was previously possible with (now phased out) third-party cookies. IMHO this is still a tracking mechanism, even if it is supposed to be more benign then other tracking methods. Further background on FloC can be found at the [EFF](https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea), [W3C](https://wicg.github.io/floc/) or [Google](https://github.com/google/ads-privacy/blob/master/proposals/FLoC/FLOC-Whitepaper-Google.pdf), to offer some different view points.
Things this project could do about FloC:
1. Not our department: We ignore it
2. Opt-Out: We set the [HTTP …
> Opt-Out of Google FloC

- cfg/conf.sample.php
- lib/Configuration.php
This follows a suggestion from HTTP Observatory:
> Restricts where `<form>` contents may be submitted by using form-action 'none', form-action 'self', or specific URIs
Fixes #778
> Disable/disallow form actions via CSP

- cfg/conf.sample.php
- lib/Configuration.php
Over with the docker container image project, we did now get bitten twice (https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/50 & https://github.com/PrivateBin/docker-nginx-fpm-alpine/issues/62) by a combination of common settings in the PHP stack and this branch attempts to alleviate that for future releases.
Because of many ([[1]](https://searchsecurity.techtarget.com/blog/Security-Bytes/Environment-variables-Should-they-be-considered-harmful), [[2]](https://en.wikipedia.org/wiki/Shellshock_(software_bug)), [[3]](https://owasp.org/www-community/attacks/Buffer_Overflow_via_Environment_Variables)) past issues around environment variables being a source of security vulnerabilities, many components used with our application limit them from being passed down into sub-processes …
> more flexible & robust configuration file path handling

- .github/workflows/tests.yml
Especially the GCM stuff may be quite large, so caching may be a good idea.
I tried following https://github.com/shivammathur/setup-php#cache-composer-dependencies
> Cache PHP modules, composer and NodeJS stuff in CI

- .github/workflows/refresh-php8.yml
Follow-up of https://github.com/PrivateBin/PrivateBin/pull/852 again
In contrast to your suggestion, @elrido, I did use GitHubs bot account again. The mails won't spam anyone, and it's actually intended for such stuff.
Also, we get a proper avatar on GitHub's commit messages etc., and of course we know it is actually GitHubs (servers) that do this change.
> Also set author for merge commit

- lib/Data/Database.php
Closes #868.
This version is currently running at https://bin.bus-hit.me.
Support running PrivateBin using `oci` by adapting to their unique constraints.
> Support running PrivateBin on OCI (Oracle Database)

- tst/I18nTest.php
The available language list is generated by reading the i18n directory
descriptor one entry at a time, so if the jbo.json happens to be the first
file written to the directory it will be on top of the list and get picked.
https://github.com/PrivateBin/PrivateBin/blob/6307c01cc66df165207bd92a98e3158146c70c82/lib/I18n.php#L196-L199
I have to assume that scrutinizer has started hitting that case, while I failed to reproduce it locally.
This is testing for an edge case. Most users browsers won't be set to "any" language, but we need
to cover this allowed and valid use case in the language detection. Or at least not fail badly.
> allow for Lojban (jbo) to be the "any" language pick

- cfg/conf.sample.php
- lib/Persistence/TrafficLimiter.php
- tst/Persistence/TrafficLimiterTest.php
Minor improvement to the trafficlimiter.
* enable support for short CIDR subnet notation, as had been documented in conf.sample.php
* fix typo in conf.sample.php
> Allow short subnet notation

- INSTALL.md
Only fixes wrong env name in INSTALL.md for GCS backend.
https://github.com/PrivateBin/PrivateBin/blob/bd308a0d3bc80b6b985fa392eaef73bc079b434a/lib/Data/GoogleCloudStorage.php#L56
> Fix wrong env name for GCS bucket

- lib/Controller.php
Sorry guys but you are a bit late to the party. 
Google [announced](https://blog.google/products/chrome/get-know-new-topics-api-privacy-sandbox/) in January that it is [discontinuing FLoC](https://www.theregister.com/2022/01/26/google_floc_topics/?td=keepreading-top) and replacing it with Privacy Sandbox.
This PR Removes the interest-cohort setting from the Permissions-Policy header.
> Replace FLoC Header with browsing-topics header

- CHANGELOG.md
- lib/Data/Database.php
This PR fixes #919, kudos to @devnull-hub-lab for reporting this.
* Avoid `SUPER` privilege when setting the `sql_mode` for MariaDB/MySQL
> Avoid SUPER privilege when setting the sql_mode for MariaDB/MySQL, fixes #919

- CHANGELOG.md
- lib/Data/Database.php
This PR fixes #943
* revert to `CREATE INDEX` without `IF NOT EXISTS` clauses, to support MySQL
This issue didn't affect MariaDB, Postgres, SQLite (same code paths, different data types) or Oracle support (different logic in those areas).
> CREATE INDEX IF NOT EXISTS is not supported as of MySQL <= 8.0

- .github/workflows/tests.yml
I expect no stuff to break or so, so let's just try to use the current recommend LTS version. (v14 will also die at some time, but Fedora e.g. still seems to use it for now by default. Likely we may upgrade soon even more.)
Ref https://nodejs.org/en/about/releases/
> chore: run tests with NodeJS 14

- .github/workflows/tests.yml
So 14 worked, let's try 16. (Actually noticed fedora uses v16 not 14 which makes sense if you see the support time.)
> Use NodeJs v16 for tests

- lib/Controller.php
Same as https://github.com/PrivateBin/docker-nginx-fpm-alpine/pull/108
Fixes https://github.com/PrivateBin/PrivateBin/issues/970
Disable the header here as it breaks links to the own site.
> Remove COOP header for now

- cfg/conf.sample.php
- lib/Configuration.php
- lib/Data/GoogleCloudStorage.php
This PR aims to add support to GCS Buckets configured to use Uniform ACL.
List of changes:
- Added a model_options parameter for model `GoogleCloudStorage` named `uniformacl` defaulting to `false`. Aims to add support for GCS buckets using unform ACL
> GCS Uniform ACL Support

- lib/Data/Database.php
- lib/Data/Filesystem.php
- lib/I18n.php
While fixing the php8 unit testing branch, which broke with the recently introduced new unit tests in master, I've experimentally enabled PHP 8.2 and got lot's of deprecation warnings, that phpunit treats as errors (which I kinda like):
> Warning: PHP Deprecated:  Use of "self" in callables is deprecated in /home/runner/work/PrivateBin/PrivateBin/lib/I18n.php on line 87
> Warning: PHP Deprecated:  Use of "self" in callables is deprecated in /home/runner/work/PrivateBin/PrivateBin/lib/Data/Filesystem.php on line 360
-- https://github.com/PrivateBin/PrivateBin/actions/runs/3318278413/jobs/5482047185
This branch should fix this in a backwards compatible manner (as in, it works from PHP 5.6 - 8.2, which we currently support).
> PHP 8.2 compatibility: Use of "self" in callables is deprecated

- .github/workflows/tests.yml
see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> handle github actions deprecation warnings

- cfg/conf.sample.php
- lib/Configuration.php
- lib/YourlsProxy.php
- tst/JsonApiTest.php
- tst/YourlsProxyTest.php
This PR fixes #1002
* improved wording of configuration items around YOURLS and basepath, as discussed in #1002
* adjust the YOURLS proxy check to detect if the passed URL is originating from the basepath
Please review and start discussions here or on the lines of code in the "files changed" view with any suggestions - this is mostly about the wording of the document and I'm not a native English speaker.
I have re-tested this and do get the shortened URL in the browser in my view after pressing the button. It was near instantaneous on my test system, so at first I didn't notice that the URL with key had gotten replaced with the short-URL, but the button did get disabled, so you can only click it once.
> improve configuration wording, adjust self check

- CHANGELOG.md
- CREDITS.md
- INSTALL.md
- bin/migrate.php
- lib/Data/AbstractData.php
- lib/Data/Database.php
- lib/Data/Filesystem.php
- lib/Data/GoogleCloudStorage.php
- lib/Data/S3Storage.php
- lib/Model.php
- tst/Bootstrap.php
- tst/ConfigurationTestGenerator.php
- tst/ControllerTest.php
- tst/ControllerWithDbTest.php
- tst/ControllerWithGcsTest.php
- tst/Data/DatabaseTest.php
- tst/Data/FilesystemTest.php
- tst/Data/GoogleCloudStorageTest.php
- tst/JsonApiTest.php
- tst/ModelTest.php
- tst/Persistence/PurgeLimiterTest.php
- tst/Persistence/ServerSaltTest.php
- tst/Persistence/TrafficLimiterTest.php
- tst/Vizhash16x16Test.php
This is a follow-up to https://github.com/PrivateBin/PrivateBin/discussions/1007
It basically adds bin/migrate.php which is a command line tool for copying or moving data between storage backends. Source and destination backends may be of different or same type. If they are of same type, their configuration must differ.
For this to work, I had to drop singleton behaviour from all storage backends and their unit tests. This also means all static properties and static member functions from AbstractData and derived classes are now instance members - with the exception of upgradePreV1Format().
> script for storage backend migrations

- CHANGELOG.md
- INSTALL.md
- cfg/conf.sample.php
- lib/Configuration.php
- lib/Model/Comment.php
- tst/IconTest
- tst/ModelTest.php
Sorry, in https://github.com/PrivateBin/PrivateBin/issues/793#issuecomment-856428488 I'd promised to also do the size and speed tests for Jdenticon, which I forgot in that PR.
I have to say that I am disappointed, having now done them and would like to revert making it the new default.
Obviously it is still good to have the extra option, so that folks can switch to it if they like the new look or an issue is discovered in one of the two older libraries.
* updated the IconCheck script to include the new library (also for the unused SVG mode - for comparison)
* reverted making Jdenticon the default, sticking with Identicon for now
TL;DR: Jdenticon takes between 9 (PHP 8.1) and 14 (PHP 7.4) times as long to generate the PNGs over Identicon and they are about double the size, but still a …
> Jdenticons size and speed test results

- cfg/conf.sample.php
- lib/Data/S3Storage.php
This PR implements #1069
* S3Storage: Use credentials array only if values are passed via config
* Instead of checking if array key exists, also checks if it's not `null` (using `isset`)
* If both values are not passed (`accesskey` and `secretkey`) don't set the `credentials` array at all
* If `credentials` array is not set, the AWS SDK will default to the default credentials provider chain, which will look for credentials in a few places automatically, including environment variables or instance roles, see [documentation](https://docs.aws.amazon.com/sdk-for-php/v3/developer-guide/guide_credentials.html#default-credential-chain)
> Feature: Allow AWS SDK to use default credential provider chain for S3Storage

- bin/administration
This PR fixes #1092, see also https://php.watch/versions/8.2/$%7Bvar%7D-string-interpolation-deprecated
> fix PHP 8.2 ${var} string interpolation deprecation

- .github/DISCUSSION_TEMPLATE/q-a.yml
1. Require to fill out STRs.
2. Add more fields for client stuff, i.e. web browser and OS.
3. Add more placeholders and descriptions to guide users.
4. Adjust the reproducibility thing to be more clear. I.e. before the result was sth. like "Issue reproducibility: Yes" - this could be confused with "Is it always reproducible? Yes", and not "It is reproducible on our test instance."
> Make QA template more strict and helpful

- .github/DISCUSSION_TEMPLATE/q-a.yml
Let's remove that.
1. With label and A&A category we have more than enough options for filtering such requests.
2. Actually, as you can see in https://github.com/orgs/PrivateBin/discussions/1152, as it is a required field, but already filled out… we want them to write proper titles. A prefilled field can just be submitted, and empty field cannot (as it is required).
> QA template: remove prefilled title

- .devcontainer/devcontainer.json
- .vscode/extensions.json
- .vscode/launch.json
This PR may fix https://github.com/PrivateBin/PrivateBin/issues/1135
Fixes https://github.com/PrivateBin/PrivateBin/issues/1135  ?
* these are just the files, when you start Codespaces, i guess from composer
> chore: commit all files initiated by coddespaces

- .github/ISSUE_TEMPLATE/config.yml
Apparently GitHub now adds a security policy button by default (this is new, is not it?)? Also they have a policy report form behind that button. So reports can apparently now be made online at GitHub? (IMHO that is fine, just need to be aware of that)
As such, IMHO two buttons would be confusing, so let's remove our custom one here?
> Remove custom security button as GitHub added own

- .github/DISCUSSION_TEMPLATE/q-a.yml
GitHub complains:
> title must be of type String and cannot be empty. [Learn more about this error.](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#key-must-be-a-string)
Well then… as we don't want to provide a default title (see https://github.com/PrivateBin/PrivateBin/pull/1155) let's remove it.
The linked doc says:
> The error can be fixed by correcting the value to be a non-empty string. If the field is not required, you should delete the key-value pair.
So that should be valid.
> Fix error message about QA template

- .github/DISCUSSION_TEMPLATE/q-a.yml
- .github/ISSUE_TEMPLATE/bug_report.md
It's apparently not enough to have in the Q/A, best is we have it here to.
The next step would be converting that into the same form like the QA template. After all, it may mostly just be copy paste as it is nearly identical but well…
> Also add FAQ section/tick box requirement for bug template

- .github/workflows/release.yml
- CHANGELOG.md
This PR (hopes to) fixes #1169 - realistically we can only test this upon the next release, so it's possible that one won't yet get the SLSA manifest attached. We will have to see and check the logs for any issues with it.
* adds workflow triggered by version tags being pushed (semver as well as the older X.Y format we used in the past)
* downloads tag tar.gz and zip files (same as used for current gpg signatures #219), calculates their sha256 hashes and feeds these into the slsa-github-generator workflow
* reformats changelog to be compatible with format understood by [parse-changelog](https://github.com/taiki-e/parse-changelog)
* extract the latest changelog entry and attach it to the drafted release as well 
Note that the changelog extraction will allow us to draft pretty complex …
> release workflow for SLSA & changelog

- .github/workflows/tests.yml
- .gitignore
It doesn't seem like we hit any new warnings or deprecations. 8.4 is obviously provisional as it's a development branch. 8.3 got released last week. Seems we are ready for it.
The only feature that looked interesting to me was the new [json_validate](https://www.php.net/manual/en/function.json-validate.php) function - I checked our use of json_decode, but in all cases we also consume the result, so we would not benefit of validating it first, as we then would be processing it twice. It is a good fit when you are just an API that stores / passes on a valid JSON without parsing it.
> enable unit testing on PHP 8.3 &  8.4 nightly

- .devcontainer/devcontainer.json
- .devcontainer/postCreateCommand.sh
This PR fixes #1209 
* Move entries in `.devcontainer/devcontainer.json#postCreateCommand` to their own file (`.devcontainer/postCreateCommand.sh`)
N/A
> move postCreateCommands to a separate file

- CHANGELOG.md
- lib/Data/Filesystem.php
- lib/I18n.php
This PR fixes #1208
* always add en to available languages
* use globs to fetch only the language files (2 and 3 letter .json files under i18n folder)
* don't add en twice
bug got introduced in 3668f1e3f4808d7232606349035c6a43c5a84c23 and started affecting release 1.6.1 after 896a49c8cf96ae9351796bd84050d2a0b249ddb3
> ensure English is always added to available languages, fixes #1208

- CHANGELOG.md
- bin/administration
- lib/Controller.php
May occur during statistics or purge, when existing pastes get parsed, addresses #1214
* Catch exceptions in statistics and around purging, report these as errors
* Failure during purge should not prevent paste creation (unless the data folder is corrupt or otherwise not writable anymore)
* Statistics will report each damaged paste ID and also include a count if any were found
* Turn some basic exceptions into error_log messages - no point in getting a stack trace for them and exceptions will end up being reported in the same place. No point in throwing exceptions that no one will ever catch, either.
> detect and report on damaged pastes

- lib/I18n.php
- tst/I18nTest.php
It gets excluded in the release archive, it's absence should not make any difference.
As per discussion in https://github.com/PrivateBin/PrivateBin/pull/1213/files/684924e9e57af8797edcc0bb48ebe3732d1a61c8#r1427426364
This PR closes #1208
> prevent regression around presence or absence of en.json

- js/common.js
- js/privatebin.js
- js/test/Helper.js
- js/test/Model.js
- js/test/PasteStatus.js
- js/test/UiHelper.js
- tpl/bootstrap.php
- tpl/page.php
This PR follows up on the discussion in https://github.com/PrivateBin/PrivateBin/pull/1227#pullrequestreview-1805108910
* fixes extractUrl regex pattern when used against JSON, XML or HTML
* adds JSON & XML samples found in YOURLS doc and HTML from our yourlsproxy template
* refactored the tests to simplify URL generation
This confirms that I misunderstood the sort, it will find the shortest URL in the string. The sort is necessary to find the right URL in the JSON & XML responses that contain both the long and short one and not in the same order.
If anyone could provide more samples API messages from other shorteners, please let us know. Now would be a good time to add them to the tests.
> add YOURLS API samples for extractUrl validation

- js/privatebin.js
As suggested in #1055 and discussed roughly with @elrido . This is our implementation of this. We were using this actually quite a long time and just forgot about submitting it back. So here we go. Please note that I wont have too much time the next weeks, so if there is anything missing to get this merged, please feel free to fork our work and make the needed changes, otherwise it might delay very long.
A short explanation:
The Link is encrypted in the browser, instead of encrypting the paste with the password, but only if burn after reading is checked. The server side encryption with the password is disable to prevent needing to enter it twice. Normal encrypted pastes remain with the same functionality.
Fixes #245
> Secure password with compatibility for burn after reading

- CHANGELOG.md
- js/privatebin.js
- tpl/bootstrap.php
- tpl/page.php
This PR fixes #606
* paste URL for email is picked from element with ID `pasteurl` instead of `window`, which should contain the shortened URL
> shortened paste URL does not appear in email

- lib/Controller.php
> Hope you don't mind that I create a PR before discussing the subject. This is such a small change than showing it is easier than explaining it :slightly_smiling_face:
Because the response from the API is PHP output, the usual `Content-Length` header is absent.
This [custom header technique](https://stackoverflow.com/questions/15097712/how-can-i-use-deflated-gzipped-content-with-an-xhr-onprogress-function/32799706#32799706) allows the client to know the total length of the data being received, in order to display a progress indicator.
Here's a code example with `XMLHttpRequest`:
```
xhr.addEventListener("progress", (e) => {
if (e.lengthComputable) {
onDownloadProgress({
loaded: e.loaded,
total: e.total,
});
} else {
const uncompressedContentLength = xhr.getResponseHeader( …
```
> Add response header `X-Uncompressed-Content-Length` for JSON API

- CHANGELOG.md
- lib/Model/AbstractModel.php
- lib/Request.php
- tst/Bootstrap.php
* Add more input sanitation, using filter_vars instead of filter_input, because our unit tests depend on manipulating global arrays, which are not used by filter_input - we would have to mock the function in the unit testing, it therefore is cleaner to use the same code paths in testing as in production. Note that some inputs in I18n and TrafficLimiter remain unfiltered, since we already validate them by other means (IP lib and/or preg_match).
* our minimum PHP version is 7.3, so we can drop the two < 5.6 fallback checks
> input sanitation & removing some obsolete version checks

- cfg/conf.sample.php
- composer.json
- doc/Installation.md
- lib/Vizhash16x16.php
- tst/Bootstrap.php
This PR improves some recently introduced changes and deals with PHP 8.1 & 8.2 deprecations that weren't flagged on the ubuntu-based github actions.
Given that the PHP 8.4 tests do currently fail with deprecation warnings in Guzzle (dependency of GCS library), phpunit seems correctly set up to fail on these, so I suspect the github php.ini defaults to a different error level than the one used in the alpine-based unit test image, where I noticed these errors after a [recent update](https://github.com/PrivateBin/docker-unit-testing/commit/da3d9f22e76f9787428522027a31e37407c0af56) (which was triggered by the ctype extension being missing in that install).
* update documentation
* clarify all template options & link to previews
* document new ctype extension requirement
* bump versions of …
> Doc'n'test mopup

- .github/workflows/tests.yml
At this time, guzzle, dependency of google cloud storage library, raises deprecation warnings in PHP 8.4, which caused the tests to be considered failed.
With this change, 8.4 will still show up as a failure, but won't prevent or interrupt the other jobs from running.
> tolerate test failures in the PHP development release

- .github/workflows/test-results.yml
- .github/workflows/tests.yml
- js/package.json
As per https://github.com/marketplace/actions/publish-test-results#use-with-matrix-strategy only one job should upload all results.
> Add upload test results job

- js/privatebin.js
Rephrase the WebAssembly error on unsupported browser
This PR fixes https://github.com/PrivateBin/PrivateBin/issues/1310
* js/privatebin.js: Rephrase error message on missing zlib support in browser
> Rephrase the WebAssembly error on unsupported browser

- CHANGELOG.md
- js/privatebin.js
- js/test/TopNav.js
- tpl/bootstrap.php
- tpl/bootstrap5.php
- tpl/page.php
This PR fixes expiration time selection for bootstrap template.
* undue the regression introduced for bootstrap5 (line 4374)
* document the template specific code paths
* add an onchange event handler for bootstrap5 & page templates
* remove unnecessary fallback in line 4572, pasteExpiration is `null` during the init call, getExpirationDefault will return the currently selected value of the select element - it would only be empty if no expirations got configured, which would cause other breakage
> expiration time selection fix for bootstrap template

- css/bootstrap5/privatebin.css
- tpl/bootstrap5.php
> bootstrap 5 attachment dropdown sizing

- css/bootstrap5/privatebin.css
- tpl/bootstrap5.php
This PR closes #1314 
* changes the plain & source code prettymessage containers into cards (border and rounded corners)
* in light mode, changes the background color of prettymessage containers and pre-blocks (for markdown) to a light grey
> bootstrap 5 code block improvements

- .github/workflows/tests.yml
Setting the platform allow composer to prevent upgrades to versions that would exceed the configured version, for the matrix tests we want to use the latest ones for that release.
> in PHP matrix tests, we don't want to constrain the platform

- tpl/bootstrap5.php
This PR fixes the width of the elements in the page to match how the old BS3 based template function, this keeps the design the same with the upgrade to BS5
Changes the container class in the new bootstrap5 template to use the full width of the screen like it used too on the old bootstrap 3 based template, by using `container-fluid` instead of `container`
After change
Before change
> Fix bootstrap5 template width

- lib/Data/Database.php
This PR addresses a [discussion in #1334](https://github.com/orgs/PrivateBin/discussions/1334#discussioncomment-9544438).
* allow skipping versions for automatic database upgrades, by using version_compare smaller-or-equal checks to match all versions up to the comparison point.
* arguably, if-conditions are more readable and/or less error prone to switch-case-statements
* while the version checks are a little less performant, this should not cause much impact as the function only gets called if the current database version is below the current installed applications, so only once after each upgrade - this is not in a hot loop
> refactor database schema upgrade to support skipping versions

- CHANGELOG.md
- css/bootstrap5/privatebin.css
This PR fixes #1349
* sets the height of the `#message` textarea to 70% of the view port height
The value was picked as a compromise to look decent over a large range of display height. You can experiment with it yourself on [one of the instances using the bootstrap5 template](https://snip.dssr.ch/) using your browsers inspect element function and setting the CSS height property of the element to various `vh` factors.
> bootstrap5 textarea height relative to viewport height

- CHANGELOG.md
- lib/Data/Database.php
This PR fixes #1361.
* Simpler PostgreSQL table lookup query, doesn't require permission to read the user table
Note that while I did validate the query on a PostgreSQL 16.1 docker container, we have no PG unit tests and I have no PrivateBin + Postgres setup available to test this on. I would appreciate if someone with a PG setup could test this branch and let us know if this causes any problems or if there would be a better/more robust/simpler query.
> Simpler PostgreSQL table lookup query

- lib/Data/Database.php
There is no way to use non persistent SQL connections as the `PDO::ATTR_PERSISTENT` is always `true` in `Database.php` file.
The PR allow to set this flag to `false` using parameter `opt[12]` from `conf.php`.
> Allow non persistent SQL connections

- lib/Configuration.php
This PR fixes `model_options[opt]` section from configuration file (`conf.php`) being ignored.
> fix(configuration): Use "model_options[opt]" section from "conf.php"

- doc/Running Unit Tests.md
I tried following the steps when running, for https://github.com/PrivateBin/PrivateBin/pull/1421, but this crucial one step is missing.
Maybe more was missing, most tests failed so hmm… but I only wanted it for the SRI generation and this was hard enough.
(And no, I did not feel like trying to run a container in a [dev]container, so these manual steps should better work.)
Maybe we can improve that further here, I the things I've noticed in this or the other PR.
> Fix phpunit doc missing crucial step of installing GCS

- CHANGELOG.md
- lib/Data/Database.php
- lib/Request.php
- tst/Bootstrap.php
- tst/Data/FilesystemTest.php
- tst/RequestTest.php
This PR fixes #1435
* added a test to trigger the issue
* fixed the issue via explicit cast
There are two other areas I found that might have the same issue, but have not been able to trigger the issue from the outside - please review and share your thoughts:
So I think that at this time both of the above cases are un-problematic, but could be potential future foot-guns if used incorrectly?
> Numeric array key type errors

- SECURITY.md
This seems to be a new feature and I've had this tested (with a different account) that this can be used by anyone.
IMHO, this is a convenient feature, as we'd need to publish it anyway there.
> Change SECURITY.md to hint for acceping vulnerability reports via the GitHub mail

- js/privatebin.js
DOMPurify removed this configuration option, so I guess it has no effect and can be removed.
See docs: https://github.com/cure53/DOMPurify?tab=readme-ov-file#removed-configuration
>  SAFE_FOR_JQUERY 	2.1.0 	No replacement required.
The PR https://github.com/cure53/DOMPurify/pull/474 also links the commits, which removed it.
> Remove SAFE_FOR_JQUERY from DOMPurify as it has been removed

- lib/Controller.php
This PR removes two `new Configuration` lines since they are not needed.
* In the Controller class, I removed a couple of lines `$this->_conf = new Configuration;`.
The Configuration class is already instanciated inside the `_init()` method.
This change improves the TTFB by almost 9%. It's not much since the load is fast already, but still.
> Do not instanciate the Configuration more than once

- lib/Controller.php
- tst/ControllerTest.php
This PR adds the possibility to load another Configuration class into the
main Controller.
The purpose is to be able to create a custom Configuration loader. Like instead
of reading a ini file, we could fetch the configuration from a database or something.
This PR depends on #1522.
- **feat: Allow to change the Configuration in the _construct**
> Allow to use another Configuration class

- bin/administration
This PR introduces **two new options** to the `bin/administration` script, improving PrivateBin's administrative capabilities:
- `--list-ids`: Lists all stored paste IDs.
- `--delete-all`: Deletes all stored pastes at once.
These features simplify maintenance and cleanup tasks, especially useful for **privacy compliance** or **bulk management** of pastes. They complement the existing `--delete` option by enabling mass operations directly from the CLI.
- Added `_list_ids()` and `_delete_all()` methods to the administration script.
- Provides informative console output for each operation, ensuring **transparency** during execution.
- Aligned with the current **coding style** and **structure** of the project.
Tested successfully in a production environment with both **filesystem** and …
> Add --delete-all option to administration script for mass paste deletion

- CHANGELOG.md
- lib/Data/Database.php
- lib/Data/Filesystem.php
This PR fixes #1554
* Added some more `error_log(...)` for catch-all failure modes in the database and filesystem store backends
> Added some more error logging for database and filesystem store backends

- CHANGELOG.md
- cfg/conf.sample.php
- lib/Configuration.php
While not strictly necessary, it would be nice to display the button icons by default in the bootstrap5 template. I hadn't noticed this in the preps for 2.0.0 release, since on my installs where I tested with bootstrap5 templates, I had already manually changed the cspheader (and template) option to match this.
* update CSP to display icons by default with bootstrap5 template
With 'self' now the default, we could remove all the explicit src-rules that already allow 'self', but that would make it more complicated for admins that _do_ want to use a bootstrap 3 based template.
Aside: I don't understand why the SVG-image-map as used for bootstrap5 does not work with just `img-src: 'self'`, which we always allowed. It somehow counts as a different type of source, only covered by the default …
> update CSP recommendation around bootstrap5 template

- lib/Configuration.php
I would like to make this little change.
Why?
Because we need to override the Configuration object.
Overriding the Configuration and not being able to use the constructed
`$_configuration` property is a shame.
* We use `protected $_configuration` instead of `private $_configuration`. This
way we can easily override the `$_configuration` property in the `Configuration` class
by using a new `Configuration` object (extending the default one).
```php
class NewConfiguration extends \PrivateBin\Configuration
{
public function __construct()
{
parent::__construct();
$this->_configuration['main']['name'] = 'Awesome PrivateBin'; // This is now possible
}
}
new \PrivateBin\Controller(new NewConfiguration()); // We use our new Configuration instance
```
This way we could perform something like this: …
> Use protected instead of private $_configuration

- BADGES.md
I noticed several of our badges don't work or link to no longer existing services. Let's remove those.
* We switched from TravisCI to Github actions
* Codacy, Code Climate & SensioLabs are not providing working reports anymore
Feel free to use this branch to add new badges if you find any that we missed.
> Remove broken & obsolete badges
